// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "DemoApiScalarGalaxy",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "DemoApiScalarGalaxy", targets: ["DemoApiScalarGalaxy"]),
    ],
    targets: [
        .target(name: "DemoApiScalarGalaxy"),
        .testTarget(name: "DemoApiScalarGalaxyTests", dependencies: ["DemoApiScalarGalaxy"]),
    ]
)

// DemoApiScalarGalaxy Swift SDK generated by Scalar SDK Generator.
