import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

// Code generated by Scalar SDK Generator. DO NOT EDIT.

public struct ClientOptions: Sendable {
    public var baseURL: URL?
    public var timeout: TimeInterval
    public var maxRetries: Int
    public var defaultHeaders: [String: String]
    public var defaultQuery: [String: String]
    public var session: URLSession
    public var decoder: JSONDecoder
    public var encoder: JSONEncoder
    public var bearerAuth: String?
    public var basicAuthUsername: String?
    public var basicAuthPassword: String?
    public var apiKeyHeader: String?
    public var apiKeyQuery: String?
    public var apiKeyCookie: String?
    public var oAuth2: String?
    public var openIDConnect: String?

    public init(
        baseURL: URL? = nil,
        timeout: TimeInterval = 60,
        maxRetries: Int = 2,
        defaultHeaders: [String: String] = [:],
        defaultQuery: [String: String] = [:],
        session: URLSession = .shared,
        decoder: JSONDecoder = JSONDecoder(),
        encoder: JSONEncoder = JSONEncoder(),
        bearerAuth: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_BEARER_AUTH"],
        basicAuthUsername: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_BASIC_AUTH_USERNAME"],
        basicAuthPassword: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_BASIC_AUTH_PASSWORD"],
        apiKeyHeader: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_API_KEY_HEADER"],
        apiKeyQuery: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_API_KEY_QUERY"],
        apiKeyCookie: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_API_KEY_COOKIE"],
        oAuth2: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_O_AUTH2"],
        openIDConnect: String? = ProcessInfo.processInfo.environment["DEMO_API_SCALAR_GALAXY_OPEN_ID_CONNECT"],
    ) {
        self.baseURL = baseURL
        self.timeout = timeout
        self.maxRetries = maxRetries
        self.defaultHeaders = defaultHeaders
        self.defaultQuery = defaultQuery
        self.session = session
        self.decoder = decoder
        self.encoder = encoder
        self.bearerAuth = bearerAuth
        self.basicAuthUsername = basicAuthUsername
        self.basicAuthPassword = basicAuthPassword
        self.apiKeyHeader = apiKeyHeader
        self.apiKeyQuery = apiKeyQuery
        self.apiKeyCookie = apiKeyCookie
        self.oAuth2 = oAuth2
        self.openIDConnect = openIDConnect
    }
}

public struct RequestOptions: Sendable {
    public var headers: [String: String]
    public var query: [String: String]
    public var timeout: TimeInterval?
    public var maxRetries: Int?
    public var idempotencyKey: String?

    public init(headers: [String: String] = [:], query: [String: String] = [:], timeout: TimeInterval? = nil, maxRetries: Int? = nil, idempotencyKey: String? = nil) {
        self.headers = headers
        self.query = query
        self.timeout = timeout
        self.maxRetries = maxRetries
        self.idempotencyKey = idempotencyKey
    }
}

public struct RawResponse<Value>: Sendable where Value: Sendable {
    public let value: Value
    public let statusCode: Int
    public let headers: [String: String]
    public let body: Data
}

public struct ResultResponse<Value: Sendable>: Sendable {
    public let value: Value
    public let statusCode: Int
    public let headers: [String: String]
    public let body: Data
    public let errorStatuses: [String]
}

public struct Page<Item: Sendable>: Sendable {
    public let items: [Item]
    public let raw: JSONValue
    public let nextCursor: String?
}

public struct StreamEvent<Value: Sendable>: Sendable {
    public let data: Value
    public let id: String?
    public let event: String?
}

public enum SDKError: Error, Sendable {
    case invalidURL(String)
    case transport(String)
    case httpStatus(statusCode: Int, headers: [String: String], body: Data, requestID: String?)
    case decoding(statusCode: Int, body: Data, underlying: String)
}

public typealias APIConnectionError = SDKError
public typealias BadRequestError = SDKError
public typealias AuthenticationError = SDKError
public typealias PermissionDeniedError = SDKError
public typealias NotFoundError = SDKError
public typealias ConflictError = SDKError
public typealias UnprocessableError = SDKError
public typealias RateLimitError = SDKError
public typealias InternalServerError = SDKError

public enum JSONValue: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JSONValue])
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null }
        else if let value = try? container.decode(Bool.self) { self = .bool(value) }
        else if let value = try? container.decode(Double.self) { self = .number(value) }
        else if let value = try? container.decode(String.self) { self = .string(value) }
        else if let value = try? container.decode([JSONValue].self) { self = .array(value) }
        else { self = .object(try container.decode([String: JSONValue].self)) }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .object(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

public final class ApiClient: @unchecked Sendable {
    private let defaultBaseURLString = "https://galaxy.scalar.com"
    private let options: ClientOptions

    public init(options: ClientOptions = ClientOptions()) {
        self.options = options
    }

    public func send<Response: Decodable & Sendable>(
        method: String,
        path: String,
        pathParams: [String: CustomStringConvertible?] = [:],
        query: [String: CustomStringConvertible?] = [:],
        headers: [String: String] = [:],
        body: Encodable? = nil,
        contentType: String? = "application/json",
        requestOptions: RequestOptions = RequestOptions(),
        responseType: Response.Type = Response.self
    ) async throws -> Response {
        let raw = try await sendRaw(method: method, path: path, pathParams: pathParams, query: query, headers: headers, body: body, contentType: contentType, requestOptions: requestOptions)
        if Response.self == EmptyResponse.self { return EmptyResponse() as! Response }
        do { return try options.decoder.decode(Response.self, from: raw.body) }
        catch { throw SDKError.decoding(statusCode: raw.statusCode, body: raw.body, underlying: String(describing: error)) }
    }

    public func sendRaw(
        method: String,
        path: String,
        pathParams: [String: CustomStringConvertible?] = [:],
        query: [String: CustomStringConvertible?] = [:],
        headers: [String: String] = [:],
        body: Encodable? = nil,
        contentType: String? = "application/json",
        requestOptions: RequestOptions = RequestOptions()
    ) async throws -> RawResponse<Data> {
        let request = try makeRequest(method: method, path: path, pathParams: pathParams, query: query, headers: headers, body: body, contentType: contentType, requestOptions: requestOptions)
        let retries = requestOptions.maxRetries ?? options.maxRetries
        var attempt = 0
        while true {
            do {
                let (data, response) = try await options.session.data(for: request)
                guard let http = response as? HTTPURLResponse else { throw SDKError.transport("Response was not HTTP") }
                let responseHeaders = normalizeHeaders(http.allHeaderFields)
                if (200..<300).contains(http.statusCode) {
                    return RawResponse(value: data, statusCode: http.statusCode, headers: responseHeaders, body: data)
                }
                if attempt < retries && shouldRetry(statusCode: http.statusCode) {
                    attempt += 1
                    try await sleepBeforeRetry(attempt: attempt, headers: responseHeaders)
                    continue
                }
                throw SDKError.httpStatus(statusCode: http.statusCode, headers: responseHeaders, body: data, requestID: responseHeaders["x-request-id"] ?? responseHeaders["X-Request-Id"])
            } catch let error as SDKError {
                throw error
            } catch {
                if attempt < retries {
                    attempt += 1
                    try await sleepBeforeRetry(attempt: attempt, headers: [:])
                    continue
                }
                throw SDKError.transport(String(describing: error))
            }
        }
    }

    public func stream<Response: Decodable & Sendable>(
        method: String,
        path: String,
        pathParams: [String: CustomStringConvertible?] = [:],
        query: [String: CustomStringConvertible?] = [:],
        headers: [String: String] = [:],
        requestOptions: RequestOptions = RequestOptions(),
        responseType: Response.Type = Response.self
    ) -> AsyncThrowingStream<StreamEvent<Response>, Error> {
        AsyncThrowingStream { continuation in
            Task {
                do {
                    let raw = try await sendRaw(method: method, path: path, pathParams: pathParams, query: query, headers: headers, body: Optional<String>.none, contentType: nil, requestOptions: requestOptions)
                    let text = String(data: raw.body, encoding: .utf8) ?? ""
                    for frame in parseSSE(text) {
                        let data = Data(frame.data.utf8)
                        let decoded = try options.decoder.decode(Response.self, from: data)
                        continuation.yield(StreamEvent(data: decoded, id: frame.id, event: frame.event))
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
        }
    }

    private func makeRequest(method: String, path: String, pathParams: [String: CustomStringConvertible?], query: [String: CustomStringConvertible?], headers: [String: String], body: Encodable?, contentType: String?, requestOptions: RequestOptions) throws -> URLRequest {
        let base: URL
        if let configuredBaseURL = options.baseURL {
            base = configuredBaseURL
        } else if let generatedBaseURL = URL(string: defaultBaseURLString) {
            base = generatedBaseURL
        } else {
            throw SDKError.invalidURL(defaultBaseURLString)
        }
        let resolvedPath = pathParams.reduce(path) { current, entry in
            current.replacingOccurrences(of: "{\(entry.key)}", with: percentEncode(String(describing: entry.value ?? "")))
        }
        guard var components = URLComponents(url: base.appendingPathComponent(resolvedPath.trimmingCharacters(in: CharacterSet(charactersIn: "/"))), resolvingAgainstBaseURL: false) else {
            throw SDKError.invalidURL(resolvedPath)
        }
        let mergedQuery = options.defaultQuery.merging(requestOptions.query) { _, new in new }
        components.queryItems = (mergedQuery.map { URLQueryItem(name: $0.key, value: $0.value) } + query.compactMap { key, value in value.map { URLQueryItem(name: key, value: String(describing: $0)) } }).sorted { $0.name < $1.name }
        guard let url = components.url else { throw SDKError.invalidURL(resolvedPath) }
        var request = URLRequest(url: url, timeoutInterval: requestOptions.timeout ?? options.timeout)
        request.httpMethod = method.uppercased()
        let mergedHeaders = options.defaultHeaders.merging(authHeaders()) { _, new in new }.merging(headers) { _, new in new }.merging(requestOptions.headers) { _, new in new }
        for (name, value) in mergedHeaders { request.setValue(value, forHTTPHeaderField: name) }
        if let key = requestOptions.idempotencyKey { request.setValue(key, forHTTPHeaderField: "Idempotency-Key") }
        if let body {
            request.httpBody = try options.encoder.encode(AnyEncodable(body))
            if let contentType { request.setValue(contentType, forHTTPHeaderField: "Content-Type") }
        }
        return request
    }

    private func authHeaders() -> [String: String] {
        var headers: [String: String] = [:]
        if let value = options.bearerAuth { headers["Authorization"] = "Bearer \(value)" }
        if let username = options.basicAuthUsername, let password = options.basicAuthPassword {
            let token = Data("\(username):\(password)".utf8).base64EncodedString()
            headers["Authorization"] = "Basic \(token)"
        }
        if let value = options.apiKeyHeader { headers["X-API-Key"] = value }
        if let value = options.apiKeyCookie { headers["Cookie"] = "api_key=" + value }
        if let value = options.oAuth2 { headers["Authorization"] = "Bearer \(value)" }
        if let value = options.openIDConnect { headers["Authorization"] = "Bearer \(value)" }
        return headers
    }
}

public struct EmptyResponse: Codable, Sendable { public init() {} }

private struct AnyEncodable: Encodable {
    private let encodeValue: (Encoder) throws -> Void
    init(_ value: Encodable) { self.encodeValue = value.encode }
    func encode(to encoder: Encoder) throws { try encodeValue(encoder) }
}

private struct SSEFrame { let data: String; let id: String?; let event: String? }

private func parseSSE(_ text: String) -> [SSEFrame] {
    var frames: [SSEFrame] = []
    var data: [String] = []
    var id: String?
    var event: String?
    func flush() {
        guard !data.isEmpty else { return }
        let joined = data.joined(separator: "\n")
        if joined != "[DONE]" { frames.append(SSEFrame(data: joined, id: id, event: event)) }
        data.removeAll(); id = nil; event = nil
    }
    for rawLine in text.split(separator: "\n", omittingEmptySubsequences: false) {
        let line = rawLine.trimmingCharacters(in: CharacterSet(charactersIn: "\r"))
        if line.isEmpty { flush(); continue }
        if line.hasPrefix(":") { continue }
        let parts = line.split(separator: ":", maxSplits: 1, omittingEmptySubsequences: false)
        let field = String(parts.first ?? "")
        let value = parts.count > 1 ? String(parts[1]).trimmingCharacters(in: .whitespaces) : ""
        if field == "data" { data.append(value) }
        if field == "id" { id = value }
        if field == "event" { event = value }
    }
    flush()
    return frames
}

private func normalizeHeaders(_ headers: [AnyHashable: Any]) -> [String: String] {
    Dictionary(uniqueKeysWithValues: headers.compactMap { key, value in
        guard let name = key as? String else { return nil }
        return (name, String(describing: value))
    })
}

private func shouldRetry(statusCode: Int) -> Bool {
    statusCode == 408 || statusCode == 409 || statusCode == 429 || (500...599).contains(statusCode)
}

private func sleepBeforeRetry(attempt: Int, headers: [String: String]) async throws {
    let retryAfterHeader = headers["Retry-After"] ?? headers["retry-after"]
    let delay = retryAfterHeader.flatMap(TimeInterval.init) ?? min(pow(2.0, Double(attempt - 1)) * 0.5, 8.0)
    try await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
}

private func percentEncode(_ value: String) -> String {
    value.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? value
}

func sdkJSONValue(_ value: Any?) -> JSONValue {
    guard let value else { return .null }
    switch value {
    case let value as JSONValue: return value
    case let value as String: return .string(value)
    case let value as Bool: return .bool(value)
    case let value as Int: return .number(Double(value))
    case let value as Double: return .number(value)
    case let value as Float: return .number(Double(value))
    case let value as [Any?]: return .array(value.map(sdkJSONValue))
    case let value as [String: Any?]: return .object(value.mapValues(sdkJSONValue))
    default: return .string(String(describing: value))
    }
}
