import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

public final class DemoApiScalarGalaxy: @unchecked Sendable {
    private let apiClient: ApiClient
    public let planets: PlanetsResource
    public let celestialBodies: CelestialBodiesResource
    public let authentication: AuthenticationResource

    public init(
        options: ClientOptions = ClientOptions(),
        bearerAuth: String? = nil,
        basicAuthUsername: String? = nil,
        basicAuthPassword: String? = nil,
        apiKeyHeader: String? = nil,
        apiKeyQuery: String? = nil,
        apiKeyCookie: String? = nil,
        oAuth2: String? = nil,
        openIDConnect: String? = nil,
    ) {
        var resolved = options
        if let bearerAuth { resolved.bearerAuth = bearerAuth }
        if let basicAuthUsername { resolved.basicAuthUsername = basicAuthUsername }
        if let basicAuthPassword { resolved.basicAuthPassword = basicAuthPassword }
        if let apiKeyHeader { resolved.apiKeyHeader = apiKeyHeader }
        if let apiKeyQuery { resolved.apiKeyQuery = apiKeyQuery }
        if let apiKeyCookie { resolved.apiKeyCookie = apiKeyCookie }
        if let oAuth2 { resolved.oAuth2 = oAuth2 }
        if let openIDConnect { resolved.openIDConnect = openIDConnect }
        self.apiClient = ApiClient(options: resolved)
        self.planets = PlanetsResource(client: apiClient)
        self.celestialBodies = CelestialBodiesResource(client: apiClient)
        self.authentication = AuthenticationResource(client: apiClient)
    }
}
