import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

public let webhookEventNames: Set<String> = ["newPlanet", "{$request.body#/successCallbackUrl}", "{$request.body#/successCallbackUrl}"]

public struct UnwrapWebhookEvent: Codable, Sendable {
    public let type: String
    public let payload: JSONValue
}

public struct RequestBodySuccessCallbackUrlWebhookEvent: Codable, Sendable {
    public let type: String
    public let payload: Planet
}

public struct RequestBodySuccessCallbackUrlWebhookEvent: Codable, Sendable {
    public let type: String
    public let payload: Planet
}

public struct WebhookEvent: Codable, Sendable {
    public let type: String
    public let payload: JSONValue
}

public func parseWebhookEvent(_ payload: Data, decoder: JSONDecoder = JSONDecoder()) throws -> WebhookEvent {
    let event = try decoder.decode(WebhookEvent.self, from: payload)
    if !webhookEventNames.isEmpty && !webhookEventNames.contains(event.type) {
        throw SDKError.transport("Unknown webhook event type: \(event.type)")
    }
    return event
}
