import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

public final class AuthenticationResource: @unchecked Sendable {
    private let client: ApiClient

    internal init(client: ApiClient) {
        self.client = client
    }

    public func createUser(params: CreateUserParams) async throws -> User {
        return try await client.send(
            method: "post",
            path: "/user/signup",
            pathParams: [:],
            query: [:],
            headers: [:],
            body: JSONValue.object(["name": sdkJSONValue(params.name), "email": sdkJSONValue(params.email), "password": sdkJSONValue(params.password)]),
            contentType: "application/json",
            requestOptions: params.requestOptions,
            responseType: User.self
        )
    }

    public struct CreateUserParams: Sendable {
        public var name: String?
        public var email: String?
        public var password: String?
        public var requestOptions: RequestOptions

        public init(
            name: String? = nil,
            email: String? = nil,
            password: String? = nil,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.name = name
            self.email = email
            self.password = password
            self.requestOptions = requestOptions
        }
    }

    public func createToken(params: CreateTokenParams) async throws -> Token {
        return try await client.send(
            method: "post",
            path: "/auth/token",
            pathParams: [:],
            query: [:],
            headers: [:],
            body: JSONValue.object(["email": sdkJSONValue(params.email), "password": sdkJSONValue(params.password)]),
            contentType: "application/json",
            requestOptions: params.requestOptions,
            responseType: Token.self
        )
    }

    public struct CreateTokenParams: Sendable {
        public var email: String?
        public var password: String?
        public var requestOptions: RequestOptions

        public init(
            email: String? = nil,
            password: String? = nil,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.email = email
            self.password = password
            self.requestOptions = requestOptions
        }
    }

    public func listMe(requestOptions: RequestOptions = RequestOptions()) async throws -> User {
        return try await client.send(
            method: "get",
            path: "/me",
            pathParams: [:],
            query: [:],
            headers: [:],
            body: nil,
            contentType: nil,
            requestOptions: requestOptions,
            responseType: User.self
        )
    }
}
