import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

public final class CelestialBodiesResource: @unchecked Sendable {
    private let client: ApiClient

    internal init(client: ApiClient) {
        self.client = client
    }

    public func create(params: CreateParams) async throws -> CelestialBody {
        return try await client.send(
            method: "post",
            path: "/celestial-bodies",
            pathParams: [:],
            query: [:],
            headers: [:],
            body: params.body,
            contentType: "application/json",
            requestOptions: params.requestOptions,
            responseType: CelestialBody.self
        )
    }

    public struct CreateParams: Sendable {
        public var body: CelestialBody
        public var requestOptions: RequestOptions

        public init(
            body: CelestialBody,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.body = body
            self.requestOptions = requestOptions
        }
    }
}
