import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

public final class PlanetsResource: @unchecked Sendable {
    private let client: ApiClient

    internal init(client: ApiClient) {
        self.client = client
    }

    public func list(params: ListParams) async throws -> JSONValue {
        return try await client.send(
            method: "get",
            path: "/planets",
            pathParams: [:],
            query: ["limit": params.limit, "offset": params.offset],
            headers: [:],
            body: nil,
            contentType: nil,
            requestOptions: params.requestOptions,
            responseType: JSONValue.self
        )
    }

    public struct ListParams: Sendable {
        public var limit: Int?
        public var offset: Int?
        public var requestOptions: RequestOptions

        public init(
            limit: Int? = nil,
            offset: Int? = nil,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.limit = limit
            self.offset = offset
            self.requestOptions = requestOptions
        }
    }

    public func create(params: CreateParams) async throws -> Planet {
        return try await client.send(
            method: "post",
            path: "/planets",
            pathParams: [:],
            query: [:],
            headers: [:],
            body: JSONValue.object(["name": sdkJSONValue(params.name), "description": sdkJSONValue(params.description), "type": sdkJSONValue(params.type), "habitabilityIndex": sdkJSONValue(params.habitabilityIndex), "physicalProperties": sdkJSONValue(params.physicalProperties), "atmosphere": sdkJSONValue(params.atmosphere), "discoveredAt": sdkJSONValue(params.discoveredAt), "image": sdkJSONValue(params.image), "satellites": sdkJSONValue(params.satellites), "creator": sdkJSONValue(params.creator), "tags": sdkJSONValue(params.tags), "successCallbackUrl": sdkJSONValue(params.successCallbackURL), "failureCallbackUrl": sdkJSONValue(params.failureCallbackURL)]),
            contentType: "application/json",
            requestOptions: params.requestOptions,
            responseType: Planet.self
        )
    }

    public struct CreateParams: Sendable {
        public var name: String?
        public var description: String?
        public var type: String?
        public var habitabilityIndex: Double?
        public var physicalProperties: JSONValue?
        public var atmosphere: [JSONValue]?
        public var discoveredAt: String?
        public var image: String?
        public var satellites: [Satellite]?
        public var creator: User?
        public var tags: [String]?
        public var successCallbackURL: String?
        public var failureCallbackURL: String?
        public var requestOptions: RequestOptions

        public init(
            name: String? = nil,
            description: String? = nil,
            type: String? = nil,
            habitabilityIndex: Double? = nil,
            physicalProperties: JSONValue? = nil,
            atmosphere: [JSONValue]? = nil,
            discoveredAt: String? = nil,
            image: String? = nil,
            satellites: [Satellite]? = nil,
            creator: User? = nil,
            tags: [String]? = nil,
            successCallbackURL: String? = nil,
            failureCallbackURL: String? = nil,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.name = name
            self.description = description
            self.type = type
            self.habitabilityIndex = habitabilityIndex
            self.physicalProperties = physicalProperties
            self.atmosphere = atmosphere
            self.discoveredAt = discoveredAt
            self.image = image
            self.satellites = satellites
            self.creator = creator
            self.tags = tags
            self.successCallbackURL = successCallbackURL
            self.failureCallbackURL = failureCallbackURL
            self.requestOptions = requestOptions
        }
    }

    public func retrieve(params: RetrieveParams) async throws -> Planet {
        return try await client.send(
            method: "get",
            path: "/planets/{planetId}",
            pathParams: ["planetId": params.planetID],
            query: [:],
            headers: [:],
            body: nil,
            contentType: nil,
            requestOptions: params.requestOptions,
            responseType: Planet.self
        )
    }

    public struct RetrieveParams: Sendable {
        public var planetID: Int
        public var requestOptions: RequestOptions

        public init(
            planetID: Int,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.planetID = planetID
            self.requestOptions = requestOptions
        }
    }

    public func update(params: UpdateParams) async throws -> Planet {
        return try await client.send(
            method: "put",
            path: "/planets/{planetId}",
            pathParams: ["planetId": params.planetID],
            query: [:],
            headers: [:],
            body: JSONValue.object(["name": sdkJSONValue(params.name), "description": sdkJSONValue(params.description), "type": sdkJSONValue(params.type), "habitabilityIndex": sdkJSONValue(params.habitabilityIndex), "physicalProperties": sdkJSONValue(params.physicalProperties), "atmosphere": sdkJSONValue(params.atmosphere), "discoveredAt": sdkJSONValue(params.discoveredAt), "image": sdkJSONValue(params.image), "satellites": sdkJSONValue(params.satellites), "creator": sdkJSONValue(params.creator), "tags": sdkJSONValue(params.tags), "successCallbackUrl": sdkJSONValue(params.successCallbackURL), "failureCallbackUrl": sdkJSONValue(params.failureCallbackURL)]),
            contentType: "application/json",
            requestOptions: params.requestOptions,
            responseType: Planet.self
        )
    }

    public struct UpdateParams: Sendable {
        public var planetID: Int
        public var name: String?
        public var description: String?
        public var type: String?
        public var habitabilityIndex: Double?
        public var physicalProperties: JSONValue?
        public var atmosphere: [JSONValue]?
        public var discoveredAt: String?
        public var image: String?
        public var satellites: [Satellite]?
        public var creator: User?
        public var tags: [String]?
        public var successCallbackURL: String?
        public var failureCallbackURL: String?
        public var requestOptions: RequestOptions

        public init(
            planetID: Int,
            name: String? = nil,
            description: String? = nil,
            type: String? = nil,
            habitabilityIndex: Double? = nil,
            physicalProperties: JSONValue? = nil,
            atmosphere: [JSONValue]? = nil,
            discoveredAt: String? = nil,
            image: String? = nil,
            satellites: [Satellite]? = nil,
            creator: User? = nil,
            tags: [String]? = nil,
            successCallbackURL: String? = nil,
            failureCallbackURL: String? = nil,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.planetID = planetID
            self.name = name
            self.description = description
            self.type = type
            self.habitabilityIndex = habitabilityIndex
            self.physicalProperties = physicalProperties
            self.atmosphere = atmosphere
            self.discoveredAt = discoveredAt
            self.image = image
            self.satellites = satellites
            self.creator = creator
            self.tags = tags
            self.successCallbackURL = successCallbackURL
            self.failureCallbackURL = failureCallbackURL
            self.requestOptions = requestOptions
        }
    }

    public func delete(params: DeleteParams) async throws -> EmptyResponse {
        return try await client.send(
            method: "delete",
            path: "/planets/{planetId}",
            pathParams: ["planetId": params.planetID],
            query: [:],
            headers: [:],
            body: nil,
            contentType: nil,
            requestOptions: params.requestOptions,
            responseType: EmptyResponse.self
        )
    }

    public struct DeleteParams: Sendable {
        public var planetID: Int
        public var requestOptions: RequestOptions

        public init(
            planetID: Int,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.planetID = planetID
            self.requestOptions = requestOptions
        }
    }

    public func uploadImage(params: UploadImageParams) async throws -> JSONValue {
        return try await client.send(
            method: "post",
            path: "/planets/{planetId}/image",
            pathParams: ["planetId": params.planetID],
            query: [:],
            headers: [:],
            body: JSONValue.object(["image": sdkJSONValue(params.image)]),
            contentType: "multipart/form-data",
            requestOptions: params.requestOptions,
            responseType: JSONValue.self
        )
    }

    public struct UploadImageParams: Sendable {
        public var planetID: Int
        public var image: Data?
        public var requestOptions: RequestOptions

        public init(
            planetID: Int,
            image: Data? = nil,
            requestOptions: RequestOptions = RequestOptions(),
        ) {
            self.planetID = planetID
            self.image = image
            self.requestOptions = requestOptions
        }
    }
}
