import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

/// Credentials to authenticate a user

public struct Credentials: Codable, Sendable, Equatable {
    public let email: String
}
