import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

/// A paginated resource

public struct PaginatedResource: Codable, Sendable, Equatable {
    public let meta: JSONValue?
}
