import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

/// A planet in the Scalar Galaxy

public struct Planet: Codable, Sendable, Equatable {
    /// Schema: readOnly
    public let id: Int
    public let name: String
    public let description: String?
    public let type: String
    /// A score from 0 to 1 indicating potential habitability
    /// Schema: minimum 0, maximum 1
    public let habitabilityIndex: Double?
    public let physicalProperties: JSONValue?
    /// Atmospheric composition
    public let atmosphere: [JSONValue]?
    public let discoveredAt: String?
    public let image: String?
    public let satellites: [Satellite]?
    /// A user
    public let creator: User?
    public let tags: [String]?
    /// Schema: readOnly
    public let lastUpdated: String?
    /// URL which gets invoked upon a successful operation
    public let successCallbackURL: String?
    /// URL which gets invoked upon a failed operation
    public let failureCallbackURL: String?

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case name = "name"
        case description = "description"
        case type = "type"
        case habitabilityIndex = "habitabilityIndex"
        case physicalProperties = "physicalProperties"
        case atmosphere = "atmosphere"
        case discoveredAt = "discoveredAt"
        case image = "image"
        case satellites = "satellites"
        case creator = "creator"
        case tags = "tags"
        case lastUpdated = "lastUpdated"
        case successCallbackURL = "successCallbackUrl"
        case failureCallbackURL = "failureCallbackUrl"
    }
}
