import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

/// Every satellite in the Scalar Galaxy

public struct Satellite: Codable, Sendable, Equatable {
    /// Schema: readOnly
    public let id: Int?
    public let name: String
    public let description: String?
    /// Diameter in kilometers
    public let diameter: Double?
    public let type: String
    public let orbit: JSONValue?
}
