import Foundation

// Code generated by Scalar SDK Generator. DO NOT EDIT.

/// A user

public struct User: Codable, Sendable, Equatable {
    /// Schema: readOnly
    public let id: Int?
    public let name: String?
}
