import XCTest
@testable import DemoApiScalarGalaxy

// Code generated by Scalar SDK Generator. DO NOT EDIT.

final class DemoApiScalarGalaxySmokeTests: XCTestCase {
    func testConstructsClient() {
        XCTAssertNotNil(DemoApiScalarGalaxy())
    }
}
